### PR TITLE
Fix boolean comparison for Document opened property

### LINKED ISSUE #95: Checking for boolValue == Boolean.TRUE won't always yield the expected result
https://github.com/digipost/digipost-api-client-java/blob/2c213dc62a1867672378a2f0fb4f0fbf0e7a623f/src/main/java/no/digipost/api/client/representations/Document.java#L122

Not all instances of `Boolean` in Java are the same object as `Boolean.TRUE`

To demonstrate:
```java
jshell> new Boolean(true) == true
$1 ==> true
jshell> new Boolean(true) == Boolean.TRUE
$2 ==> false
jshell> new Boolean("true") == true
$3 ==> true
jshell> new Boolean("true") == Boolean.TRUE
$4 ==> false
```
I know these two constructors are deprecated and their usage is rare, but nevertheless possible.

Please consider using 
```java
Boolean.TRUE.equals()
```
which is as safe, but works as expected:
```java
jshell> Boolean.TRUE.equals(new Boolean(true))
$6 ==> true
jshell> Boolean.TRUE.equals(new Boolean("true"))
$7 ==> true
jshell> Boolean.TRUE.equals(null)
$8 ==> false
```

### PR DESCRIPTION
**Pull request by Valentin-Paramonov**
Resolves  [#95](https://github.com/digipost/digipost-api-client-java/issues/95)

### CODE REVIEW

**Review by runeflobakk — APPROVED** [review]
Thank you for the fix and tests!

**Comment by runeflobakk** [comment]
And, may I add, you name the tests exactly by my preference! 😉

**Comment by Valentin-Paramonov** [comment]
Thank you for reviewing :+1:

**Comment by runeflobakk** [comment]
Included in release 13.2: https://search.maven.org/artifact/no.digipost/digipost-api-client-java/13.2/jar

**Pull request merged**
